app_name="ara"

template_dir="res/templates"
[server]
port=9000

[security]
password_expiry_days=365
user_activation_token_expiry_mins=15
user_password_reset_token_expiry_mins=15
secret_key="71ade6e0-51b1-4aa3-aa70-682ea7566d3f"

