refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} - {l:>5.5} {f}:{L} - {M}:{t} - {T} - {m}{n}"
  file:
    kind: file
    path: "../target/ara.log"
    encoder:
      pattern: "{d} - {l:>5.5} - {M:>15.15} - {m}{n}"
root:
  level: debug
  appenders:
  - file
loggers:
  launch:
    level: info
    appenders:
    - file
    - stdout
  app::requests:
    level: info
    appenders:
    - file
    additive: false